/*
 * IRC - Internet Relay Chat, ircd/version.c
 * Copyright (C) 1990 Chelsea Ashley Dyerman
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 1, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/*
 * This file is generated by version.c.SH. Any changes made will go away.
 */

#include "sys.h"
#include "h.h"
#include "s_debug.h"
#include "patchlevel.h"
#include "patchlist.h"
#include "version.h"

const char *generation = "1";
const char *creation = "Mon 27 Apr CEST at 2020 01:16:31 PM";
const char *version = BASE_VERSION RELEASE "222" PATCHLIST;

const char *infotext[] = {
    "IRC --",
    "Based on the original code written by Jarkko Oikarinen, version 2.6:",
    "Copyright 1988, 1989, 1990, 1991 University of Oulu, Computing Center",
    "",
    "Wiz      Jarkko Oikarinen    <jto@tolsun.oulu.fi>",
    "",
    "This program is free software; you can redistribute it and/or",
    "modify it under the terms of the GNU General Public License as",
    "published by the Free Software Foundation; either version 2, or",
    "(at your option) any later version.",
    "",
    "The UnderNet code is based upon version 2.8.10.",
    "The main developers of version 2.7 and 2.8 are:",
    "",
    "Avalon    Darren Reed       <avalon@coombs.anu.edu.au>",
    "msa       Markku Savela     <msa@tel4.tel.vtt.fi>",
    "Wumpus    Greg Lindahl      <lindahl@pbm.com>",
    "",
    "The main developer of version u2.9 and u2.10 is:",
    "",
    "Run           Carlo Wood        <carlo@runaway.xs4all.nl>",
    "",
    "Thanks goes to all other people who contributed to any version.",
    "A full listing of all coders can be found in doc/Authors in the",
    "source.  Contributers to version u2.10 can be found on",
    "http://coder-com.undernet.org/posters.html",
    "Thanks also to those who provided me with accounts; the kind sys",
    "admins who let me and others continue to develop IRC.",
    "",
    "Desarrollador principal de IRC-Hispano y ESNET:",
    "jcea        Jesus Cea        <jcea@argo.es>",
    "",
    "Otros desarrolladores para IRC-Hispano:",
    "|savage|      Jordi Murgo        <savage@apostols.org>",
    "FreeMind      Daniel Fernandez   <dfm@unr.com>",
    "zoltan        Toni Garcia        <zoltan@irc-dev.net>",
    "Amn3S1A      Miguel A. Fosas     <amn3s1a@irc-dev.net>",
    "NiKoLaS      Ruben Cardenal      <nikolas@irc-dev.net>",
    "mount        Jorge Duarte        <mount@irc-dev.net>",
    "RyDeN        Alberto Alonso      <ryden@redhispana.org>",
    "",
    "Para mas informacion sobre el ircd visita",
    "http://www.irc-dev.net",
    "",
    "[62777    44] [11333   204] [61042    66] [06426   172]",
    "[61454    19] [42017    24] [23427    20]",
    0,
};
